#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"

chown -R "$app:www-data" "$install_dir"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

ynh_go_install

pushd $install_dir/build/
	GOCACHE=/root/go/cache GOOS=js GOARCH=wasm go build -ldflags="-s -w" index.go
popd

ynh_go_remove
ynh_safe_rm "$install_dir/build/"
ynh_safe_rm "$install_dir/.cache/"
ynh_safe_rm "$install_dir/go/"
ynh_safe_rm "$install_dir/.go-version"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
